version: '3.8'

name: lepedo

services:
  app:
    build:
      context: .
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    env_file:
      - .env
    restart: always
    networks:
      - lepedo-network
    depends_on:
      - db

  db:
    image: postgres:13.10
    env_file:
      - .env
    restart: always
    volumes:
      - lepedo_db_folder:/var/lib/postgresql/data
    networks:
      - lepedo-network

volumes:
  lepedo_db_folder:
    external: true

networks:
  lepedo-network:
