version: '3.8'

name: kirkuty

services:
  app:
    build:
      context: .
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    env_file:
      - .env
    restart: always
    networks:
      - kirkuty-network
    volumes:
      - kirkuty_images:/app/static
    depends_on:
      - db

  db:
    image: postgres:13.10
    env_file:
      - .env
    restart: always
    volumes:
      - kirkuty_db_folder:/var/lib/postgresql/data
    networks:
      - kirkuty-network

volumes:
  kirkuty_db_folder:
    external: true

  kirkuty_images:
    external: true

networks:
  kirkuty-network:
